---
image: docker:stable

services:
  - docker:dind

stages:
  - build

build_image:
  stage: build
  before_script:
    - docker login -u ${REGISTRY_USER} -p ${REGISTRY_PASSWORD} ${REGISTRY_HOST}
    - apk add make jq curl wget
  script:
    - export OPENSHIFT_RELEASE=$(make print_version)
    - make fetch
    - make build
    - make test
    - make push
  parallel:
    matrix:
      - DEPLOYMENT_TYPE: ocp
        RELEASE_CHANNEL:
          - stable-4.14
          - stable-4.15
          - stable-4.16
          - stable-4.17
  only:
    - master
