collections:
  - name: ansible.netcommon
    version: 8.6.2
  - name: ansible.posix
    version: 2.2.2
  - name: ansible.utils
    version: 6.1.0
  - name: community.crypto
    version: 3.3.0
  - name: community.general
    version: 13.3.0
  - name: community.hashi_vault
    version: 7.1.0
  - name: kubernetes.core
    version: 6.5.0
  - name: kubevirt.core
    version: 2.3.0
  - name: community.vmware
    version: 6.2.1
